// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/metadata.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_GetPlayerName_FullMethodName   = "/proto.MetadataService/GetPlayerName"
	MetadataService_SetPlayerName_FullMethodName   = "/proto.MetadataService/SetPlayerName"
	MetadataService_SetPlayerStatus_FullMethodName = "/proto.MetadataService/SetPlayerStatus"
	MetadataService_GetPlayerStatus_FullMethodName = "/proto.MetadataService/GetPlayerStatus"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	// Get display name for a given player ID
	GetPlayerName(ctx context.Context, in *GetPlayerNameRequest, opts ...grpc.CallOption) (*GetPlayerNameResponse, error)
	// Set/Update display name for a player ID (e.g., on creation or change)
	SetPlayerName(ctx context.Context, in *SetPlayerNameRequest, opts ...grpc.CallOption) (*SetPlayerNameResponse, error)
	SetPlayerStatus(ctx context.Context, in *SetPlayerStatusRequest, opts ...grpc.CallOption) (*SetPlayerStatusResponse, error)
	GetPlayerStatus(ctx context.Context, in *GetPlayerStatusRequest, opts ...grpc.CallOption) (*GetPlayerStatusResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetPlayerName(ctx context.Context, in *GetPlayerNameRequest, opts ...grpc.CallOption) (*GetPlayerNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerNameResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetPlayerName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SetPlayerName(ctx context.Context, in *SetPlayerNameRequest, opts ...grpc.CallOption) (*SetPlayerNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPlayerNameResponse)
	err := c.cc.Invoke(ctx, MetadataService_SetPlayerName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SetPlayerStatus(ctx context.Context, in *SetPlayerStatusRequest, opts ...grpc.CallOption) (*SetPlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPlayerStatusResponse)
	err := c.cc.Invoke(ctx, MetadataService_SetPlayerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetPlayerStatus(ctx context.Context, in *GetPlayerStatusRequest, opts ...grpc.CallOption) (*GetPlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerStatusResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetPlayerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	// Get display name for a given player ID
	GetPlayerName(context.Context, *GetPlayerNameRequest) (*GetPlayerNameResponse, error)
	// Set/Update display name for a player ID (e.g., on creation or change)
	SetPlayerName(context.Context, *SetPlayerNameRequest) (*SetPlayerNameResponse, error)
	SetPlayerStatus(context.Context, *SetPlayerStatusRequest) (*SetPlayerStatusResponse, error)
	GetPlayerStatus(context.Context, *GetPlayerStatusRequest) (*GetPlayerStatusResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) GetPlayerName(context.Context, *GetPlayerNameRequest) (*GetPlayerNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerName not implemented")
}
func (UnimplementedMetadataServiceServer) SetPlayerName(context.Context, *SetPlayerNameRequest) (*SetPlayerNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlayerName not implemented")
}
func (UnimplementedMetadataServiceServer) SetPlayerStatus(context.Context, *SetPlayerStatusRequest) (*SetPlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlayerStatus not implemented")
}
func (UnimplementedMetadataServiceServer) GetPlayerStatus(context.Context, *GetPlayerStatusRequest) (*GetPlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStatus not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_GetPlayerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetPlayerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetPlayerName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetPlayerName(ctx, req.(*GetPlayerNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SetPlayerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SetPlayerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_SetPlayerName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SetPlayerName(ctx, req.(*SetPlayerNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SetPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SetPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_SetPlayerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SetPlayerStatus(ctx, req.(*SetPlayerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetPlayerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetPlayerStatus(ctx, req.(*GetPlayerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerName",
			Handler:    _MetadataService_GetPlayerName_Handler,
		},
		{
			MethodName: "SetPlayerName",
			Handler:    _MetadataService_SetPlayerName_Handler,
		},
		{
			MethodName: "SetPlayerStatus",
			Handler:    _MetadataService_SetPlayerStatus_Handler,
		},
		{
			MethodName: "GetPlayerStatus",
			Handler:    _MetadataService_GetPlayerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metadata.proto",
}
